### ISSUE TITLE
output colored image

### ISSUE THREAD

**Issue by naseeresmael** [tzm1003306213/JRN4SR#1]
Hi @tzm1003306213 , thank you for your work ,  i test it and it work great, just want to get the output scaled photo with full colore anstedof gray photo, can you please explane to me how to do that.

**Comment by tzm1003306213** [comment]
You can obtain the color image through upscale the chrominance channels using bicubic interpolation.

**Comment by naseeresmael** [comment]
ok , thank you very much for your quic replay.
